#!/bin/sh -e
#
# 2023,2024 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of the skonfig set __unbound.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer prints the currently set options from unbound.conf
# (and unbound.conf.d/remote-control.conf)
#

# NOTE: sync with files/params.sh
set -- /etc/unbound/unbound.conf
test -r "$1" || exit 0  # this file is required
for _f in /etc/unbound/unbound.conf.d/remote-control.conf
do
	test -r "${_f}" || continue
	set -- "$@" "${_f}"
done
unset -v _f

# DEBUG
# echo '#files:' "$@"

awk '
{ sub(/^[ \t]*/, "") }

/^#/ { next }

/^(auth-zone|forward-zone|include|include-toplevel|ipset|rpz|stub-zone|view):/ {
	# ignore these sections (they are named or do not contain options)
	SECTION = ""
	next
}

/^(auth-zone|cachedb|dnscrypt|dnstap|dynlib|forward-zone|include|include-toplevel|ipset|python|remote-control|rpz|server|stub-zone|view):/ {
	SECTION = substr($0, 1, index($0, ":")-1)
	next
}

SECTION && /: / {
	printf "%s:%s\n", SECTION, $0
}
' "$@"
