#!/bin/sh -e
#
# 2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of the skonfig set __unbound.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#
# This explorer prints the currently set options from unbound.conf
#

# NOTE: sync with files/params.sh
test -r /etc/unbound/unbound.conf || exit 0

awk '
{ sub(/[ \t]*/, "") }

/^#/ { next }

/^[ \t]*(auth-zone|cachedb|dnscrypt|dnstap|dynlib|forward-zone|include|include-toplevel|ipset|python|remote-control|rpz|server|stub-zone|view):/ {
	sub(/[ \t]*/, "")
	SECTION = substr($0, 1, index($0, ":")-1)
	next
}

/./ { printf "%s:%s\n", SECTION, $0 }
' /etc/unbound/unbound.conf
